### ISSUE TITLE
Not running single spec

### ISSUE THREAD

**Issue by Gamatora** [paulz/Kiwi-CedarShortcuts#1]
I have  > 50 Spec in my project, it takes more than 60 seconds to run, making it hard to do TDD or GUTs.

This tool works partially: it runs a set of Spec (~10%) including the one being focused. But it _doesn't_ run only the focused Spec.

With latest Kiwi / XCode.

**Comment by paulz** [comment]
Thank you, @Gamatora, you right, this pod runs all examples of spec. I've update the description and docs to reflect that and added FAQ: https://github.com/paulz/Kiwi-CedarShortcuts#frequetly-asked-questions

**Comment by Gamatora** [comment]
Yeah, thanks :+1:!
